# Generated by Django 5.1.5 on 2025-01-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=400)),
                ("short_url", models.CharField(default="", max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expiration_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("visits", models.IntegerField(default=0)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_date", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.CharField(max_length=200)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "short_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="urlshortenerapp.shortenedurl",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Access logs",
            },
        ),
    ]
