# Generated by Django 5.1.5 on 2025-01-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortenerapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accesslog",
            old_name="access_date",
            new_name="accessed_at",
        ),
    ]
