# Generated by Django 5.1.5 on 2025-01-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortenerapp", "0002_rename_access_date_accesslog_accessed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="expiration_hours",
            field=models.IntegerField(default=24),
        ),
    ]
