# Generated by Django 5.1.5 on 2025-01-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortenerapp", "0003_shortenedurl_expiration_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
