# Generated by Django 5.1.5 on 2025-01-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortenerapp", "0004_alter_accesslog_id_alter_shortenedurl_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
