# Generated by Django 5.1.5 on 2025-01-22 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortenerapp", "0006_alter_accesslog_id_alter_shortenedurl_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="expiration_hours",
            field=models.IntegerField(
                default=24,
                validators=[django.core.validators.MaxValueValidator(10000000)],
            ),
        ),
    ]
